export const NAMESPACE = 'USER';

export default {
  CLEAR: 'CLEAR',
  STATE: 'STATE',
  VALIDATION: 'VALIDATION',
  CLEAR_VALIDATION_COUPON: 'CLEAR_VALIDATION_COUPON',
  PREMIUM: 'PREMIUM',
  FRESH_SIGNUP: 'FRESH_SIGNUP',
  USER_LANGUGE: 'USER_LANGUGE',
};
